include: "configs/base.yaml"

paths:
  # Ordner mit den WAVs, die du inferieren willst
  infer_raw_dir:  "${root_dir}/Raw_Infer"
  # Wohin die geschnittenen 16k-Snippets für die Inferenz kommen
  infer_processed_dir: "${root_dir}/processed_16k_infer"
  # Wohin die CSVs & Raven-Labels kommen
  infer_outputs_dir:   "${root_dir}/Inference_Results"

#model:
  # explizite Modell-Datei (überschreibt models_dir/best_model.keras)
  #path: "${root_dir}/Bioacoustic-Frog-Detection/models/best_model.keras"

preprocess:
  sr_orig: 44100
  sr_target: 16000
  window_size: 2.0
  overlap: 0.5
  lowcut: 700.0
  highcut: 4000.0
  bp_order: 5
  n_jobs: 4
  use_labels: False

yamnet:
  hub_url: "https://tfhub.dev/google/yamnet/1"
  batch_size: 64

infer:
  threshold: 0.35
  merge_gap: 0      # max. Lücke zwischen Treffern, die zusammengeschoben werden
  min_event_len: 2   # zu kurze Events verwerfen
  low_freq_hz: 700     # in Raven-Datei
  high_freq_hz: 4000   # in Raven-Datei
  species_label: "Frog"