include: "configs/base.yaml"
model:
  input_dim: 1024
  units: 256
  n_layers: 1
  dropout: 0.2
  focal_alpha: 0.75
  focal_gamma: 2.0
  learning_rate: 0.0005

train:
  batch_size: 32
  epochs: 50
  patience: 10
  min_delta: 0.0001
  val_split: 0.2
  pos_weight: 1.0
  threshold: 0.5